# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'dytv' do
  pod 'Alamofire', '~> 4.2.0'
  pod 'Kingfisher'
  pod 'LeanCloud', '~> 10.0.0'
  use_frameworks!




end
